### csv valid
POST http://localhost:8082/setblock
Authorization: Basic user:password
content-type: application/octet-stream
X-Payload-Type: csv
X-World-Name: world

< ./test_data/1.csv

### bin valid

POST http://localhost:8082/setblock
Authorization: Basic user:password
content-type: application/octet-stream
X-Payload-Type: bin
X-World-Name: world

< ./test_data/2.dat

### get worlds

GET http://localhost:8082/worlds

### invalid csv

POST http://localhost:8082/setblock
Authorization: Basic user:password
content-type: application/octet-stream
X-Payload-Type: csv
X-World-Name: world

< ./test_data/2.dat

### invalid bin

POST http://localhost:8082/setblock
Authorization: Basic user:password
content-type: application/octet-stream
X-Payload-Type: bin
X-World-Name: world

< ./test_data/1.csv

### empty bin

POST http://localhost:8082/setblock
Authorization: Basic user:password
content-type: application/octet-stream
X-Payload-Type: bin
X-World-Name: world

< ./test_data/0.csv

### big update

POST http://localhost:8082/setblock
Authorization: Basic user:password
content-type: application/octet-stream
X-Payload-Type: bin
X-World-Name: world

< ./test_data/output.dat

### request chunk

GET http://localhost:8082/getblock
?world_name=world
&minx=0
&minz=0
&sizex=20
&sizez=20
Authorization: Basic user:password
X-Payload-Type: bin
